// Minimal repro: verify that inkwell 0.9 + LLVM 22.1.8 verify / MCJIT work.
use inkwell::context::Context;
use inkwell::values::BasicMetadataValueEnum;
use inkwell::OptimizationLevel;

fn main() {
    let context = Context::create();
    let module = context.create_module("probe");
    let i64_ty = context.i64_type();
    let i8_ptr_ty = context.ptr_type(inkwell::AddressSpace::from(0u16));

    // Isomorphic to the module generated by printstr.aero: main + printf + a global string
    let printf_ty = i8_ptr_ty.fn_type(&[i8_ptr_ty.into()], true);
    let printf = module.add_function("printf", printf_ty, None);
    let _abort = module.add_function("abort", context.void_type().fn_type(&[], false), None);
    let main = module.add_function("main", i64_ty.fn_type(&[], false), None);

    let builder = context.create_builder();
    let entry = context.append_basic_block(main, "entry");
    builder.position_at_end(entry);

    let gv = builder.build_global_string_ptr("hello from probe\n", "str_0").unwrap();
    let fmt = gv.as_pointer_value();
    let call_args: [BasicMetadataValueEnum; 1] = [fmt.into()];
    builder.build_call(printf, &call_args, "printf").unwrap();
    builder.build_return(Some(&i64_ty.const_zero())).unwrap();

    eprintln!("[probe] SKIPPING verify, going straight to JIT");
    eprintln!("[probe] creating JIT engine");
    let engine = match module.create_jit_execution_engine(OptimizationLevel::None) {
        Ok(e) => e,
        Err(e) => {
            eprintln!("[probe] JIT engine FAILED: {e}");
            return;
        }
    };
    unsafe {
        match engine.get_function::<unsafe extern "C" fn() -> i64>("main") {
            Ok(f) => {
                eprintln!("[probe] calling main");
                f.call();
                eprintln!("[probe] JIT call done");
            }
            Err(e) => eprintln!("[probe] get_function FAILED: {e}"),
        }
    }
    eprintln!("[probe] all done");
}
