// Generated by `aero build --cpp`. Do not edit.
// Aero -> C++ bindings. Link against the Aero-built shared library.

#ifndef AERO_CPP_BIND_HPP
#define AERO_CPP_BIND_HPP

#include <cstdint>

extern "C" {
int64_t add(int64_t a, int64_t b);
// symbol `double` is a C++ keyword; callable as `double_`
double double_(double x) asm("double");
bool is_even(int64_t n);
int64_t str_len(const char* s);
} // extern "C"

#endif // AERO_CPP_BIND_HPP
