// Generated by `aero build --cpp`. Do not edit.
// Aero -> C++ bindings. Link against the Aero-built shared library.

#ifndef AERO_EXPORT_DEMO_HPP
#define AERO_EXPORT_DEMO_HPP

#include <cstdint>

extern "C" {
int64_t add(int64_t a, int64_t b);
// symbol `double` is a C++ keyword; callable as `double_`
double double_(double x) asm("double");
bool is_even(int64_t n);
} // extern "C"

#endif // AERO_EXPORT_DEMO_HPP
